config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs do
    post 'toggle_confirmed', on: :member
  end  
  resources :users do
    post 'toggle_activity', on: :member
  end
  resources :beers
  resources :styles
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  resources :ratings, only: [:index, :new, :create, :destroy]
  get 'signup', to: 'users#new'
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to:'places#index'
  get 'places/:id', to:'places#show'
  post 'places', to:'places#search'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, -> { distinct }, through: :memberships, source: :user

  def to_s
    "#{name} "
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beer_clubs = case order
                  when 'name' then @beer_clubs.sort_by(&:name)
                  when 'founded' then @beer_clubs.sort_by(&:founded)
                  when 'city' then @beer_clubs.sort_by(&:city)
                  end
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @rating = Rating.new
    @rating.beer = @beer
    @membership = Membership.new
    @membership.beer_club = @beer_club
    @memberships = @beer_club.memberships.where(confirmed: true)
    @memberships.each do |m|
      if m.beer_club == @beer_club && m.user == current_user && m.confirmed == true
        @member = true
        @membership = Membership.find_by(user_id: current_user.id, beer_club_id: @beer_club.id)
      end
    end
    @applications = Membership.all.where(beer_club_id: @beer_club.id, confirmed: nil)
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)
    Membership.create(beer_club_id: @beer_club.id, user_id: current_user.id, confirmed: true)
    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    if current_user.admin
      @beer_club.destroy
      respond_to do |format|
        format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to beer_club_path, notice: 'You are not an admin'
    end
  end

  def toggle_confirmed
    @membership = Membership.find(params[:id])
    @memberships = Membership.all.where(confirmed: true)
    @memberships.each do |m|
      if m.beer_club == @membership.beer_club && m.user == current_user && m.confirmed == true
        @member = true
      end
    end
    if @member
      membership = Membership.find(params[:id])
      membership.update_attribute :confirmed, true

      redirect_to membership_path, notice: "Membership confirmed"
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club, local: true) do |form| %>
  <% if beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Name" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter name for beer club" %>
  </div>

  <div class="form-group">
    <%= form.label :founded, "Founded" %>
    <%= form.text_field :founded, class: "form-control", placeholder: "Give founding year" %>
  </div>

  <div class="form-group">
    <%= form.label :city, "City" %>
    <%= form.text_field :city, class: "form-control", placeholder: "Enter city" %>
  </div>

  <button type="submit" class="btn btn-primary">Create beer club</button>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h1>Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th> <%= link_to 'Name', beer_clubs_path(order:"name") %> </th>
      <th> <%= link_to 'Founded', beer_clubs_path(order:"founded") %> </th>
      <th> <%= link_to 'City', beer_clubs_path(order:"city") %> </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= beer_club.name %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club %></td>
        <td><%= link_to('Edit', edit_beer_club_path(beer_club)) if current_user %></td>
        <td><%= link_to('Destroy', beer_club, method: :delete, data: { confirm: 'Are you sure?' }) if current_user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to('New Beer Club', new_beer_club_path, class:"btn btn-primary") if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @beer_club.name %>
</p>

<p>
  <strong>Founded:</strong>
  <%= @beer_club.founded %>
</p>

<p>
  <strong>City:</strong>
  <%= @beer_club.city %>
</p>

<p>
  <strong>Members:</strong>
  <% @memberships.each do |member| %>
    <%= link_to member.user.username, member %>
  <% end %>
</p>

<% if current_user && @member %>
  <p>
    <strong>Applications:</strong>
    <% @applications.each do |application| %>
      <%= link_to application.user.username, application %>
      <%= link_to "Confirm", toggle_confirmed_beer_club_path(application.id), method: :post, class: "btn btn-primary" %>
    <% end %>
  </p>
<% end %>

<% if current_user && !@member %>
  <%= form_for(@membership) do |f| %>
    <%= f.hidden_field :beer_club_id %>
    <%= f.submit value:"join the club", class:"btn btn-primary" %>
  <% end %>
  <p></p>
<% end %>

<% if current_user && @member %>
  <%= form_for(@membership, method: "delete") do |f| %>
    <%= f.hidden_field :beer_club_id %>
    <%= f.submit value: "end the membership", class:"btn btn-danger" %>
  <% end %>
  <p></p>
<% end %>  

<%= link_to('Edit', edit_beer_club_path(@beer_club)) if current_user %> |
<%= link_to 'Back', beer_clubs_path %>