config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs do
    post 'toggle_confirmed', on: :member
  end  
  resources :users do
    post 'toggle_activity', on: :member
  end
  resources :beers
  resources :styles
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  resources :ratings, only: [:index, :new, :create, :destroy]
  get 'signup', to: 'users#new'
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to:'places#index'
  get 'places/:id', to:'places#show'
  post 'places', to:'places#search'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ratings, dependent: :destroy # käyttäjällä on monta ratingia
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  validates :username, uniqueness: true,
                       length: { minimum: 3, maximum: 30 }
  validates :password, format: { with: /^(?=.*?[A-Z])(?=.*\d)[\w-]{4,30}$/, multiline: true, message: "must be at least 4 characters and include one number and one Uppercase letter." }

  has_secure_password

  include RatingAverage

  def favorite_beer
    return nil if ratings.empty?

    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_style
    favorite(:style)
  end

  def favorite_brewery
    favorite(:brewery)
  end

  def favorite(groupped_by)
    return nil if ratings.empty?

    grouped_ratings = ratings.group_by{ |r| r.beer.send(groupped_by) }
    averages = grouped_ratings.map do |group, ratings|
      { group: group, score: average_of(ratings) }
    end

    averages.max_by{ |r| r[:score] }[:group]
  end

  def average_of(ratings)
    ratings.sum(&:score).to_f / ratings.count
  end

  def self.top(amount)
    raters = User.all.sort { |u| -u.ratings.count }
    raters.take(amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings, :beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @favorite_style = @user.favorite_style
    if @user.favorite_brewery
      @favorite_brewery = @user.favorite_brewery.name
    end
    if current_user
      if current_user.admin
        @admin = true
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? && @user == current_user && @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    user = User.find params[:id]
    user.delete if current_user == user
    # nollataan sessio
    session[:user_id] = nil
    # uudelleenohjataan sovellus pääsivulle
    redirect_to :root
  end

  def toggle_activity
    user = User.find(params[:id])
    user.update_attribute :active, !user.active

    new_status = user.active? ? "active" : "closed"

    redirect_to user, notice: "user activity status changed to #{new_status}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :password %><br />
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password for <%= @user.username %></h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if current_user.admin and !user.active? %>
            <span class="label label-info">account frozen</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:"btn btn-primary" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2>
  <strong><%= @user.username %></strong>
  <% if not @user.active  %>
    <span class="badge badge-danger">Account closed</span>
  <% end %>
</h2>
<% if @admin && @user.active %>
  <%= link_to 'Close account', toggle_activity_user_path(@user.id), method: :post, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<% end %>
<% if @admin && !@user.active %>
  <%= link_to 'Open account', toggle_activity_user_path(@user.id), method: :post, class:"btn btn-primary" %>
<% end %>
<p>
has made <%= @user.ratings.count %> ratings, average rating <%= round(@user.average_rating) %>
</p>
<h3>ratings</h3>
<ul>
  <% @user.ratings.each do |rating| %>
    <li>
      <%= rating %>
      <% if @user == current_user %>
          <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' }, id: rating.id %>
      <% end %>
    </li>
  <% end %>
</ul>
<h3>beerclubs</h3>
<ul>
<% @user.beer_clubs.each do |club| %>
    <li> <%= link_to club, beer_club_path(club.id) %> </li>
<% end %>
</ul>
<p></p>
<% if @favorite_style %>
  <p> favorite beer style <%= @favorite_style.name %> </p>
<% end %>
<p></p>
<% if @favorite_brewery %>
  <p> favorite brewery <%= @favorite_brewery %> </p>
<% end %>
<p></p>
<% if @user == current_user %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', users_path %>